spring:
  application:
    name: cottage-user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: -1ms

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8080
